apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server
    spec:
      containers:
      - image: nginx
        name: nginx